# Site settings
title: 书半生
header-img: "img/page-bg8.jpg"
tagline: "cn"
description: ""
baseurl: ""
url: ""

# Social Account
douban_username: 

# About/contact
owner: 
  name: "aleng_zhang"
  email: aleng_zhang@outlook.com
  bio: ""

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "aleng_zhang"
      header-img: "img/page-bg5.jpg" # We don't want posts without a header image, that whould mean white on white